version: "3.1"
services:
  jenkins:
    build:
      context: jenkins
    image: myjenkins
    container_name: jenkins
    ports:
     - "8080:8080"
    # depends_on:
    #  - nexus
    # links:
    #   - nexus
    volumes:
     - "./jenkins/jobs:/var/jenkins_home/jobs/"
     - "./jenkins/m2deps:/var/jenkins_home/.m2/repository/"
     - "./jenkins/downloads:/var/jenkins_home/downloads"
    environment:
     - NEXUS_RELEASES_URL=http://nexus:8081/repository/maven-releases/
     - NEXUS_SNAPSHOTS_URL=http://nexus:8081/repository/maven-snapshots/
#    cpus: '0.50'
#    mem_limit: '256M'
#     secrets:
#      - nexusPassword
#   nexus:
#     image: sonatype/nexus3
#     container_name: nexus
#     ports:
#      - "8081:8081"
#     volumes:
#      - "./nexus-data:/nexus-data"
# #    cpus: '0.50'
# #    mem_limit: '256M'
# secrets:
#  nexusPassword:
#   file: ./secrets/nexusPassword
